version: "3"
services:
  controlpanel:
    build: .
    ports:
      - 58888:3000
    environment:
      - TARGET_CONTAINER_NAME: "jitsi_prosody_1"
    volumes:
      - ./:/ctlpanel
      - /var/run/docker.sock:/var/run/docker.sock
